### ISSUE TITLE
nuclear waste disposal drum update

### ISSUE THREAD

**Issue by undeadyeti** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#13]
currently when you break a nuclear waste disposal drum it drops every thing in it which kind of defeats the point of it being a waste storage drum needs to be updated to where when broken it holds its contents

**Comment by CharleyJQ** [comment]
Thank you for the suggestion; Expected release is Milestone 1.6.1

**Comment by itech2018** [comment]
Compleated in latest
