### ISSUE TITLE
turret AI glitch

### ISSUE THREAD

**Issue by undeadyeti** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#19]
not sure if it was a glitch or a bug went mining in the nether for about 15min went about 1.2k in the nether tp back home infront of my turret and it was saying the ownership on the turret wasn't there so i procced to get fired at by my own turret not sure y because i added my self to it a few hours ago and its been fine but for some reason that tp from the nether to my base deleted me off its friendly list not a big issue thought id list it just for feature reference

**Comment by undeadyeti** [comment]
turret was the light machine gun turret

**Comment by CharleyJQ** [comment]
At this time, We are unable to recreate this bug. If you can leave any more information that would be great. Or even let us know if this issue happens again and we will once again try to recreate the issue.
