### ISSUE TITLE
Crash when using armor with step sound (corrupted sound file)

### ISSUE THREAD

**Issue by AbraKadabra1** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#20]
"Error in class 'CodecJOrbis' 
 Ogg header not recognized in method 'readHeader'. "

After digging in mod files, and finding iron1.ogg in "assets\hbm\sounds\footsteps\" it becomes obvious that's file is corrupted. It won't open nor with VLC, nor AIMP, nor Windows media player and don't have any information. Changing it with any other ogg from the same folder, fixes the problem.

-Win11
-Mod ver: 1.6.1
-Forge: 14.23.5.2860

**Comment by CharleyJQ** [comment]
Hi there, Thanks for the report we will look into this for you!

**Comment by CharleyJQ** [comment]
After speaking with the dev team; This bug was already caught, And as of this moment has been fixed we will be pushing the fix ASAP.
