### ISSUE TITLE
Suggestion: Add a config option to disable "Press O For duck"

### ISSUE THREAD

**Issue by Ashen-sysadmin** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#24]
Trying to work on a modpack including HBM, and this has been bugging me more than it needs to. 

I just want a way to disable this feature so my modpack can feel more thematically cohesive. I can't just change the control to an unused key, because HBM doesn't allow remapping the "duck" key.

**Comment by CharleyJQ** [comment]
Hi There, Thanks for the suggestion. They is already a option in the config files to disable this.

 Go to the following path

Minecraft location > Config > HBM > hbm.cfg > Line 62 |  B:1.28_enableDuckButton=true
Then set the true to false to disable this setting. Then in your modpack make sure to include the configs folder.

Thanks :)
