### ISSUE TITLE
Launch Button

### ISSUE THREAD

**Issue by Russian1965** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#25]
add a covered launch button that u need a key to open then it emits a permeant redstone signal until pressed again.

when a key is inserted it opens the cover, when you press the button once it stays pressed until you push it again, once pressed it emits a redstone signal of 15.

**Comment by CharleyJQ** [comment]
Hi Russian1965,

Thanks for the suggestion, We will look into this and will get back to you as soon as possible!

**Comment by CharleyJQ** [comment]
This has already been suggested please see the related suggestion! #12
