### ISSUE TITLE
Add the flux network mod to the server 

### ISSUE THREAD

**Issue by undeadyeti** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#26]
Please add flux network to the pack so we can transfer power with out cables plus it also allows us to transfer eu power to rf 
https://www.curseforge.com/minecraft/mc-mods/flux-networks

**Comment by CharleyJQ** [comment]
At this moment; It will not be added. Power can be transfered using a "Energy Accepter" (RF - KAE); For future suggestions of mods to the modpack please post them on this GiTHub page please. Thank you! :)
