### ISSUE TITLE
Crash while exploring Twilight Forest on server

### ISSUE THREAD

**Issue by aking4125** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#27]
Hello,

Upon exploring the twilight forest, clients are crashing with the following report:

[crash-2023-11-12_16.39.58-client.txt.zip](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/files/13328679/crash-2023-11-12_16.39.58-client.txt.zip)

[latest.log.gz](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/files/13328680/latest.log.gz)

In the log, HBM is referenced multiple times. The original crash report doesn't seem to give too much information.

Any ideas?

**Comment by itech2018** [comment]
I noticed in your reply you said some clients. Is this just happening to a select few people

**Comment by aking4125** [comment]
Yes. I am so far unaffected. At least in those same chunks. Since I'm about 2k blocks away from them. 

I'm testing the world save on a SP world to see what is up in that area.

**Comment by itech2018** [comment]
Yeah let me know what happens with a test in single player as the log file and crash log at a quick look dont seem very helpfull

**Comment by aking4125** [comment]
Yeah. CensoredASM is pointing directly to HBM and those repeated crashes found in the .log file. HBM is referenced the most for some reason. Then the references stop, points to bewitchment, then points to nothing else. So I'm a tad confused as to what is happening.

Since HBM is referenced the most, that's why I posted this here for a tiny bit of insight knowing full well it doesn't contain any useful information.

**Comment by itech2018** [comment]
Yeah HBM Can often get the blame for it due to errors from things like textures of removed blocks that have been removed but the physical block has been left behind for backwords compatibility

**Comment by aking4125** [comment]
Referenced this issue to Gregtech since the single-player crash now points directly to Gregtech. Further complicating the issue I guess. 

Also its not just some clients, confirmed to be everybody.

**Comment by aking4125** [comment]
This issue is unrelated to HBM as it was just a packet-sending problem. Gregtech seems to be the cause. May reopen if anything HBM-related shows up. See the mentioned issue for details.
