### ISSUE TITLE
[Siren Audio] Subnautica siren and Cyclops death quote (maybe)

### ISSUE THREAD

**Issue by YuRaihn** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#32]
I offer to add the siren tapes with Cyclops underwater boat's hull damage siren and voiceline of Cyclops about hull failure.

Siren possible source link: https://www.youtube.com/watch?v=FAHPZB8M69k

Cyclops possible voicelines: https://www.youtube.com/watch?v=g4HJ4k0lmws&t (needed quote: 0:22)

Quote: "Emergency! Hull failure imminent! Abandon ship!"

**Comment by CharleyJQ** [comment]
Unable to be used, Due to copyright. Subnautica audio is copyrighted.
