### ISSUE TITLE
Suggestion: Ore Generation Config. 

### ISSUE THREAD

**Issue by Ashen-sysadmin** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#34]
It would help to be able to disable generation of mod ores in the config. Either because they are duplicates, or because modpack devs want to implement custom generation.

**Comment by CharleyJQ** [comment]
Hey MerrittK, Thank you for the suggestion! We are going to look into this and see what we can do to get this added!

**Comment by Ashen-sysadmin** [comment]
It looks like the mod has ore configs in hbm_dimensions.cfg, but deleting the values there causes crashes.

**Comment by CharleyJQ** [comment]
Deleting the values or changing the values?

**Comment by Ashen-sysadmin** [comment]
Changing works I think,

**Comment by Ashen-sysadmin** [comment]
So I was able to disable it, by setting amount to gen to zero.
