### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by VladSog** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#39]
**Describe the bug**
Incorrect texture of steel scaffold

**To Reproduce**
Steps to reproduce the behaviour:
1. Install mod
2. Launch Minecraft
3. Place scaffold

**Expected behaviour**
texture will be white, not gray as it should be

**Screenshots**
![image](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/assets/161121586/5017d3ca-dcee-4202-9d33-d84a39f8e552)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Forge Version: 14.23.5.2860

**Additional context**
It's a small bug, but it's very annoying.

**Comment by CharleyJQ** [comment]
Hi There Vlad, This isn't exactly an issue. The intentions we have for this is to be able to make the steel paintable. Meaning its default colour will be white to then allow the user to paint this to the colour they wish. We have set the colour to white already while we're working on the paintable features.

Thanks,

Coldalliance

**Comment by VladSog** [comment]
OK, it'll be cooler than the original mod)

**Comment by VladSog** [comment]
And make the scaffolding be generated gray in naturally generated structures (if you can do it)
