### ISSUE TITLE
Watz reactor does not function.

### ISSUE THREAD

**Issue by ToukoMan** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#40]
I built the Watz reactor the way the marker showed it to me but when i right click on an access hatch i just get yelled at by the reactor saying: "Error: Reactor Structure is not valid!".
Making the Watz just tell you where the issue is would be enough other than it not functioning.

**Comment by CharleyJQ** [comment]
Hey there, Thanks for the ticket, Can you provide some screenshots of this for us to help assist you on this issue?

**Comment by ToukoMan** [comment]
First image
![2024-04-20_11 12 32](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/assets/167606598/084c571d-0cf2-4ed2-bbeb-e290c556b7f2)
what it looks like on the inside 
![2024-04-20_11 14 06](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/assets/167606598/5f820c16-b1be-43a6-acf7-69c355b15b3f)
and i do rebuild that part before hitting the access hatch.

**Comment by CharleyJQ** [comment]
Hey, Sorry for our delay. Can you confirm what you've built the outside of the reactor with? Was it with the Watz Reactor Stability Element?

**Comment by ToukoMan** [comment]
Yes i made it out of Watz Reactor Stability Element.
![2024-04-29_20 25 27](https://github.com/Hamster-Systems/Hbm-s-Nuclear-Tech-GIT/assets/167606598/f5b1b857-f230-4bc3-aba7-3d64ee4de843)

**Comment by CharleyJQ** [comment]
So yeah these are the incorrect materials, The material you wanted to use is the Reinforced Bricks. We have posted a video to assist with this, https://youtu.be/JWpaU3U9t4Y Please let me know if this helps.

**Comment by ToukoMan** [comment]
Thanks it works now.

**Comment by CharleyJQ** [comment]
Great! Glad to hear! Will close this now :)
